duyuo/duyuo/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^', include('user_registration.urls')),
    url(r'^admin/', admin.site.urls),
    #url('', include('social.apps.django_app.urls', namespace='social')),
    url('', include('social_django.urls', namespace='social')),
    url('', include('django.contrib.auth.urls', namespace='auth')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

duyuo/user_registration/urls.py
from django.conf.urls import url

from . import views

app_name = 'user_registration'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^register$', views.register, name='register'),
    url(r'^accounts/register', views.register_user, name='register_user'),
    url(r'^accounts/login$', views.login_user, name='login_user'),
    url(r'^accounts/logout', views.logout_user, name='logout_user'),
    url(r'^accounts/profile$', views.user_profile, name='user_profile'),
    url(r'^accounts/profile/update', views.update_profile, name='update_profile'),
    url(r'^profile/education', views.user_education, name='user_education'),
    url(r'^profile/base-interests$', views.base_interests, name='base_interests'),
    url(r'^profile/base-interests/answer', views.answer_questionnaire, name='answer_questionnaire'),
    url(r'^profile/results', views.profile_results, name='profile_results'),
    url(r'^contact$', views.send_us_email, name='send_us_email'),
    url(r'^privacy', views.privacy, name='privacy'),
    url(r'^terms-of-use', views.terms, name='terms'),
    url(r'^accounts/login/visitor', views.visitor, name='visitor')
]

duyuo/user_registration/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import ModelChoiceField, ModelForm
from .models import HighSchool, Question

#from user_registration.models import UserProfile


class RegistrationForm(UserCreationForm):
    email = forms.EmailField(required=False)
    password1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = (
            'username',
            'email',
            #'first_name',
            #'last_name',
            'password1',
            'password2'
        )

    def clean_password2(self):
        # Check that the two password entries match
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords don't match")
        return password2

    def save(self, commit=True):
        # Save the provided password in hashed format
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user

class LoginForm(AuthenticationForm):
    def confirm_login_allowed(self, user):
        user = super(LoginForm, self)

        return user

class EducationForm(forms.Form):
    school = ModelChoiceField(queryset=HighSchool.objects.all().order_by('name') , empty_label="Other")
    id_number = forms.IntegerField()
    current_grade = forms.CharField(max_length=20)
    nsc_type = forms.CharField(max_length=25)

duyuo/user_registration/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.utils import timezone
from django.db.models import Avg
from django.template.response import TemplateResponse
from .models import Question, UserProfile, HighSchool, ExaminationType
from .models import QuestionAnswer, DomainCard, Post, Video
import logging
import operator

from user_registration.forms import (
    RegistrationForm,
    LoginForm,
    EducationForm
)
from django.contrib import auth
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash, logout
from django.contrib.auth.decorators import login_required
from django.template.context import RequestContext
from django.shortcuts import render_to_response
from django.core.mail import send_mail

def index(request):
	registration_form = RegistrationForm()
	login_form = LoginForm()

	args = {'registration_form': registration_form, 'login_form': login_form}

	if request.user.is_authenticated():
		domain_cards = DomainCard.objects.all()
		posts = Post.objects.all()
		videos = Video.objects.all()
		user_has_interests = QuestionAnswer.objects.filter(user=request.user).exists()
		if user_has_interests:
			all_objects = QuestionAnswer.objects.filter(user=request.user)

			realistic_avg = all_objects.filter(question__question_group__description="Realistic").aggregate(Avg('answer'))
			investigative_avg = all_objects.filter(question__question_group__description="Investigative").aggregate(Avg('answer'))
			social_avg = all_objects.filter(question__question_group__description="Social").aggregate(Avg('answer'))
			artist_avg = all_objects.filter(question__question_group__description="Artist").aggregate(Avg('answer'))
			enterprising_avg = all_objects.filter(question__question_group__description="Enterprising").aggregate(Avg('answer'))
			conventional_avg = all_objects.filter(question__question_group__description="Conventional").aggregate(Avg('answer'))

			if all_objects:
				x = {"Realistic" : realistic_avg['answer__avg'],
						"Investigative" : investigative_avg['answer__avg'],
						"Social" : social_avg['answer__avg'],
						"Artistic" : artist_avg['answer__avg'],
						"Enterprising" : enterprising_avg['answer__avg'],
						"Conventional" : conventional_avg['answer__avg']}

				temp_results = sorted(x.items(), key=operator.itemgetter(1))
				results = temp_results[0:3] #returns 3 elements
				if results is not None:
					domain_cards = domain_cards.exclude(domain__name="Education", phase__name__in=list(dict(results).keys()))	
				
		args['cards'] = domain_cards
		args['user_has_interests'] = user_has_interests
		args['posts'] = posts
		args['videos'] = videos
	
	return render(request, 'user_registration/base.html')





	#context = RequestContext(request,{'request': request,'user': request.user,
	#	'registration_form': registration_form, 'login_form': login_form})
	#return render_to_response('user_registration/index.html',context)

def register(request):
	registration_form = RegistrationForm()

	args = {'registration_form': registration_form}
	#return TemplateResponse(request, 'user_registration/register.html', {})
	return render(request, 'user_registration/register.html', args)

	#context = RequestContext(request,{'request': request,'user': request.user,
	#	'registration_form': registration_form})
	#return render_to_response('user_registration/register.html',context)

def visitor(request):
		user = auth.authenticate(username="Visitor", password="Known321")

		if user is not None:
			if user.is_active:
				auth.login(request,user)
				return HttpResponseRedirect('/')

		args = {'registration_form': registration_form, 'login_form': login_form}
		return render(request, 'user_registration/index.html', args)

def register_user(request):
	if request.method =='POST':
		form = RegistrationForm(request.POST)
		if form.is_valid():
			form.save()

			username = form.cleaned_data['username']
			password = form.cleaned_data['password1']
			user = auth.authenticate(username=username, password=password)

			if user is not None:
				if user.is_active:
					auth.login(request,user)
					return HttpResponseRedirect('/')
		else:
			return HttpResponseRedirect('/register')
	else:
		registration_form = RegistrationForm()
		login_form = LoginForm()

		args = {'registration_form': registration_form, 'login_form': login_form}
		return render(request, 'user_registration/index.html', args)

def login_user(request):
	if request.method =='POST':
		form = LoginForm(data=request.POST)
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			user = auth.authenticate(username=username, password=password)

			if user is not None:
				if user.is_active:
					auth.login(request,user)
					return HttpResponseRedirect('/')
		else:
			return HttpResponseRedirect('/')
	else:
		registration_form = RegistrationForm()
		login_form = LoginForm()

		args = {'registration_form': registration_form, 'login_form': login_form}
		return render(request, 'user_registration/index.html', args)

def logout_user(request):
	logout(request)
	return redirect(reverse('user_registration:index'))

def user_profile(request):
	high_school_data = HighSchool.objects.all().order_by('name')
	examination_type_data = ExaminationType.objects.all()

	try:
		profile_data = UserProfile.objects.get(user=request.user)
		args = {'profile_data' : profile_data}
	except :
		args = {'profile_data' : None}
	
	#if profile_data :
	#	args = {'profile_data' : profile_data}
	#else:
	#	args = {'profile_data' : None}

	args['high_school_data'] = high_school_data
	args['examination_type_data'] = examination_type_data
	return render(request, 'user_registration/create_profile.html', args)

def user_education(request):
	education_form = EducationForm()
	args = {'education_form' : education_form}
	return render(request, 'user_registration/education_questions.html', args)

def base_interests(request):
	question_list = Question.objects.all()
	args = {'question_list' : question_list}
	return render(request, 'user_registration/base_interests.html', args)

def privacy(request):
	return render(request, 'user_registration/privacy.html', {})

def terms(request):
	return render(request, 'user_registration/terms.html', {})

def update_profile(request):
	logging.warning('About to start reading form')
	if request.method =='POST':

		post_args = dict(request.POST)

		logging.warning('Form has : %s', post_args)
		current_user = User.objects.get(username=request.user.username)

		first_name = post_args['first_name'][0]
		last_name = post_args['last_name'][0]
		identity_number = post_args['identity_number'][0]
		school_name = post_args['school_name'][0]
		grade = post_args['grade'][0]
		nsc_type = post_args['nsc_type'][0]
		cell_number = post_args['cell_number'][0]
		email = post_args['email'][0]

		current_user.first_name = first_name
		current_user.last_name = last_name
		current_user.email = email

		profile_data = UserProfile.objects.update_or_create(
			user=request.user,
			defaults = {'grade' : grade, 'id_number': identity_number, 'nsc_type' : nsc_type,
					'school_name' : school_name, 'cell_number' : cell_number})

		#profile_data.user = request.user
		#profile_data.grade = grade
		#profile_data.school_name = school_name
		#profile_data.id_number =  identity_number
		#profile_data.nsc_type =  nsc_type
		#profile_data.cell_number =  cell_number

		current_user.save()
		#profile_data.save()

		profile_data = UserProfile.objects.get(user=request.user)
		args = {'profile_data' : profile_data, 'result' : "Success"}
		return render(request, 'user_registration/create_profile.html', args)
	else:
		profile_data = UserProfile.objects.get(user=request.user)
		args = {'profile_data' : profile_data, 'result' : "Failure"}
		return render(request, 'user_registration/create_profile.html', args)

def answer_questionnaire(request):
	if request.method =='POST':
		logging.warning(dict(request.POST))
		question_count = Question.objects.all().count()

		for q_id, answer_val in request.POST.items():
			if q_id.isdigit():
				key_question = Question.objects.get(pk=q_id)

				answer_data = QuestionAnswer.objects.update_or_create(
					user = request.user,
					question = key_question,
					defaults = {'answer' : answer_val}
					)
		args = {}
		return redirect(reverse('user_registration:profile_results'))
	else:
		return redirect(reverse('user_registration:index'))

def profile_results(request):
	all_objects = QuestionAnswer.objects.filter(user=request.user)

	realistic_avg = all_objects.filter(question__question_group__description="Realistic").aggregate(Avg('answer'))
	investigative_avg = all_objects.filter(question__question_group__description="Investigative").aggregate(Avg('answer'))
	social_avg = all_objects.filter(question__question_group__description="Social").aggregate(Avg('answer'))
	artist_avg = all_objects.filter(question__question_group__description="Artist").aggregate(Avg('answer'))
	enterprising_avg = all_objects.filter(question__question_group__description="Enterprising").aggregate(Avg('answer'))
	conventional_avg = all_objects.filter(question__question_group__description="Conventional").aggregate(Avg('answer'))

	if all_objects:
		x = {"Realistic" : realistic_avg['answer__avg'],
				"Investigative" : investigative_avg['answer__avg'],
				"Social" : social_avg['answer__avg'],
				"Artistic" : artist_avg['answer__avg'],
				"Enterprising" : enterprising_avg['answer__avg'],
				"Conventional" : conventional_avg['answer__avg']}

		results = sorted(x.items(), key=operator.itemgetter(1),reverse=True)
		args = {'results' : results}

		return render(request, 'user_registration/profile_results.html', args)
	else:
		args = {}
		return render(request, 'user_registration/profile_results.html', args)

def send_us_email(request):
	if request.method == 'POST':

duyuo/user_registration/templates/user_registration/base_interests.html
{% extends "./base.html" %}
{% load static %}

{% block title %}Your Interests{% endblock title %}


{% block inner_body %}

<section id="register" class="bg-primary center-align">
    <div class="container">
        {% if user and not user.is_anonymous %}
        <div class="section">
        <img src="{% static 'user_registration/img/icons_user2.png' %}" class="responsive-img" alt="{{ user.get_full_name|default:user.username }}">
        </div>

      <div class="divider"></div>
      <div class="section">

        <h3>Okay {{ user.get_full_name|default:user.username }}</h3>

        <div class="row">
          <div class="col s12 12 12">
            <div class="card-panel teal">
              <span class="white-text">Now we need to get to know you a little better. This will help us help you find what you need.
              Let's answer a few questions below and take it from there, you ready?
              </span>
            </div>
          </div>
        </div>

        <div class="row">
          <div class="col s12 12 12">
            <div class="card light-blue darken-4">
              <span class="card-title white-text">Rate from 1 - 5
              </span>
            </div>
          </div>
        </div>

        <form class="col s12 12 12 form" method="POST" action="{% url 'user_registration:answer_questionnaire' %}">{% csrf_token %}
        <!-- Realistic Question card -->
        <div class="row">
          <div class="col s12 12 12">
            <div class="card light-blue darken-1">
              <div class="card-content black-text">
                <span class="card-title">Realistic</span>

                <ul class="collection with-header">
                {% for instance in question_list %}
                  {% ifequal instance.question_group|stringformat:"s" "Realistic" %}
                  <li class="collection-item">
                    <div class="row">
                    <div class="col s12 m9">
                        <h6 class="left-align">{{instance.question}}</h6>
                    </div>
                    <div class="col s12 m3">
                    <p class="range-field">
                      <input type="range" id="{{ instance.id }}" name="{{ instance.id }}" min="1" max="5"></input>
                    </p>

                    </div>
                  </div>
                  </li>
                  {% endifequal %}
                {% endfor %}
                </ul>

              </div>
              <div class="card-action">
              </div>
            </div>
          </div>
        </div>
        <!-- /Realistic Question card -->

        <!-- Investigative Question card -->
        <div class="row">
          <div class="col s12 12 12">
            <div class="card amber">
              <div class="card-content black-text">
                <span class="card-title">Investigative</span>

                <ul class="collection with-header">
                {% for instance in question_list %}
                  {% ifequal instance.question_group|stringformat:"s" "Investigative" %}
                  <li class="collection-item">
                    <div class="row">
                    <div class="col s12 m9">
                        <h6 class="left-align">{{instance.question}}</h6>
                    </div>
                    <div class="col s12 m3">
                    <p class="range-field">
                      <input type="range" id="{{ instance.id }}" name="{{ instance.id }}" min="1" max="5"></input>
                    </p>

                    </div>
                  </div>
                  </li>
                  {% endifequal %}
                {% endfor %}
                </ul>


              </div>
              <div class="card-action">
              </div>
            </div>
          </div>
        </div>
        <!-- /Investigative Question card -->

        <!-- Social Question card -->
        <div class="row">
          <div class="col s12 12 12">
            <div class="card lime accent-3">
              <div class="card-content black-text">
                <span class="card-title">Social</span>

                <ul class="collection with-header">
                {% for instance in question_list %}
                  {% ifequal instance.question_group|stringformat:"s" "Social" %}
                  <li class="collection-item">
                    <div class="row">
                    <div class="col s12 m9">
                        <h6 class="left-align">{{instance.question}}</h6>
                    </div>
                    <div class="col s12 m3">
                    <p class="range-field">
                      <input type="range" id="{{ instance.id }}" name="{{ instance.id }}" min="1" max="5"></input>
                    </p>

                    </div>
                  </div>
                  </li>
                  {% endifequal %}
                {% endfor %}
                </ul>

              </div>
              <div class="card-action">
              </div>
            </div>
          </div>
        </div>
        <!-- /Social Question card -->

        <!-- Artist Question card -->
        <div class="row">
          <div class="col s12 12 12">
            <div class="card pink darken-1">
              <div class="card-content black-text">
                <span class="card-title">Artistic</span>

                <ul class="collection with-header">
                {% for instance in question_list %}
                  {% ifequal instance.question_group|stringformat:"s" "Artist" %}
                  <li class="collection-item">
                    <div class="row">
                    <div class="col s12 m9">
                        <h6 class="left-align">{{instance.question}}</h6>
                    </div>
                    <div class="col s12 m3">
                    <p class="range-field">
                      <input type="range" id="{{ instance.id }}" name="{{ instance.id }}" min="1" max="5"></input>
                    </p>

                    </div>
                  </div>
                  </li>
                  {% endifequal %}
                {% endfor %}
                </ul>

              </div>
              <div class="card-action">
              </div>
            </div>
          </div>
        </div>
        <!-- /Artist Question card -->

        <!-- Enterprising Question card -->
        <div class="row">
          <div class="col s12 12 12">
            <div class="card light-blue darken-1">
              <div class="card-content black-text">
                <span class="card-title">Enterprising</span>

                <ul class="collection with-header">
                {% for instance in question_list %}
                  {% ifequal instance.question_group|stringformat:"s" "Enterprising" %}
                  <li class="collection-item">
                  <div class="row">
                    <div class="col s12 m9">
                        <h6 class="left-align">{{instance.question}}</h6>
                    </div>
                    <div class="col s12 m3">
                    <p class="range-field">
                      <input type="range" id="{{ instance.id }}" name="{{ instance.id }}" min="1" max="5"></input>
                    </p>

                    </div>
                  </div>
                  </li>
                  {% endifequal %}
                {% endfor %}
                </ul>

              </div>
              <div class="card-action">
              </div>
            </div>
          </div>
        </div>
        <!-- /Enterprising Question card -->

        <!-- Conventional Question card -->
        <div class="row">
          <div class="col s12 12 12">
            <div class="card red accent-3">
              <div class="card-content black-text">
                <span class="card-title">Conventional</span>

                <ul class="collection with-header">
                {% for instance in question_list %}
                  {% ifequal instance.question_group|stringformat:"s" "Conventional" %}
                  <li class="collection-item">
                    <div class="row">
                    <div class="col s12 m9">
                        <h6 class="left-align">{{instance.question}}</h6>
                    </div>
                    <div class="col s12 m3">
                    <p class="range-field">
                      <input type="range" id="{{ instance.id }}" name="{{ instance.id }}" min="1" max="5"></input>
                    </p>

                    </div>
                  </div>
                  </li>
                  {% endifequal %}
                {% endfor %}
                </ul>

              </div>
              <div class="card-action">
              </div>
            </div>
          </div>
        </div>
        <!-- /Conventional Question card -->

        <button type="submit" value="" class="btn btn-large" > Done!</button>

        </form>
      </div>
    {% endif %}

    </div>
</section>

{% endblock inner_body %}

duyuo/user_registration/templates/user_registration/education_questions.html
{% extends "./base.html" %}
{% load static %}

{% block title %}Create Profile{% endblock title %}


{% block inner_body %}

<section class="cta">
    <div class="cta-content">
        <div class="container">
            <div class="section-heading">
                <h3>What does your education look like?</h3>
                <p>We will us the information to find you opportunities</p>
                <hr>
            </div>
            <form action="{% url 'user_registration:user_education' %}" method="POST" class="form-horizontal">
            {% csrf_token %}
                {{ education_form.as_p }}
                <div class="form-group">
                    <div class="col offset-2 col s8 8 8">
                        <button type="submit" value="user_education" class="btn btn-outline btn-xl page-scroll">Let's Go!</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="overlay"></div>
</section>

<section id="contact" class="contact bg-primary">
    <div class="container">
        <h2>We <i class="fa fa-heart"></i> new friends!</h2>
        <ul class="list-inline list-social">
            <li class="social-twitter">
                <a href="#"><i class="fa fa-twitter"></i></a>
            </li>
            <li class="social-facebook">
                <a href="#"><i class="fa fa-facebook"></i></a>
            </li>
            <li class="social-google-plus">
                <a href="#"><i class="fa fa-google-plus"></i></a>
            </li>
        </ul>
    </div>
</section>

{% endblock inner_body %}

duyuo/user_registration/templates/user_registration/index.html
{% extends "./base.html" %}
{% load static %}

{% block register_login %}
<div id="profile" class="container">
{% if user and not user.is_anonymous %}
	
	<div class="section">
	<img src="{% static 'user_registration/img/icons_user2.png' %}" class="responsive-img" alt="{{ user.get_full_name|default:user.username }}">
    </div>

  <div class="divider"></div>
  <div class="section">
  
    <h3>Hello {{ user.get_full_name|default:user.username }}!</h3>

	<ul class="collapsible light-blue darken-1" data-collapsible="accordion">
	  <li>
	    <div class="collapsible-header">Update your information
	    	<a href="{% url 'user_registration:user_profile' %}" class="secondary-content"><i class="material-icons">send</i></a>
	    </div>
	    <div class="collapsible-body"><p>This is where you can update your personal information. Things run smoothly when we have accurate information</p></div>
	  </li>
	  <li>
	    <div class="collapsible-header">Update your interests
	    	<a href="{% url 'user_registration:base_interests' %}" class="secondary-content"><i class="material-icons">send</i></a>
	    </div>
	    <div class="collapsible-body"><p>This is where you update your interests, so we can find the most suitable information for your needs.</p></div>
	  </li>
	  <li>
	    <div class="collapsible-header">Browse education info
	    	<a href="#!" class="secondary-content"><i class="material-icons">lock</i></a>
	    </div>
	    <div class="collapsible-body"><p>Here you can find our database of education information. Whether it is for opportunities while in highschool or for post high school, you can find something here.</p></div>
	  </li>
	  <li>
	    <div class="collapsible-header">Browse entrepreneur info
	    	<a href="#!" class="secondary-content"><i class="material-icons">lock</i></a>
	    </div>
	    <div class="collapsible-body"><p>This is a collection of informaiton that is useful for budding entrepreneurs.</p></div>
	  </li>
	</ul>

    <a type="button" href="{% url 'auth:logout' %}?next={{ request.path }}"
    class="btn btn-outline btn-xl page-scroll" > Logout</a>
  </div>
  {% else %}
	<!--
  <h5>Login with a social media account</h5>
  	<div class="divider"></div>
  	<br>
	<div class="row">
		<div class="col s4">
			<a href="{% url 'social:begin' 'facebook' %}?next={{ request.path }}">
	    <img src="{% static 'user_registration/img/triangle_facebook.png' %}" class="responsive-img" alt="Login with Facebook">
	    </a>
		</div>
		<div class="col s4">
			<a href="{% url 'social:begin' 'google-oauth2' %}?next={{ request.path }}">
	    <img src="{% static 'user_registration/img/triangle_google_plus.png' %}" class="responsive-img" alt="Login with Google">
	    </a>
		</div>
		<div class="col s4">
	    	<a href="{% url 'social:begin' 'twitter' %}?next={{ request.path }}">
	    <img src="{% static 'user_registration/img/triangle_twitter.png' %}" class="responsive-img" alt="Login with Twitter">
	    </a>
		</div>
	</div>
  	<div class="divider"></div>
	-->
	
	<div class="section">
	  <h5>Login</h5>

	  <!-- <a type="button" class="btn btn-outline btn-large" href="{% url 'user_registration:visitor' %}">Try Visitor Mode</a> -->

	  <form action="{% url 'user_registration:login_user' %}" method="POST" class="form">{% csrf_token %}
		{{ login_form.as_p }}
	  	<div class="form-group">
	  		<div class="col-sm-2"></div>
	    	<div class="col-sm-8">
	      		<button type="submit" value="login_user" class="btn btn-outline btn-xl page-scroll">Login</button>
	    	</div>
			<div class="col-sm-2"></div>
	  	</div>
		</form>
	</div>
	<br>
	<h5>Register Now?</h5>
	<a type="button" class="btn btn-outline btn-xl page-scroll" href="{% url 'user_registration:register' %}">Register</a>

	<h5>Later?</h5>
	<a type="button" class="btn btn-outline btn-xl page-scroll" href="#home">Not Now</a>
    {% endif %}
</div>
{% endblock %}

duyuo/user_registration/templates/user_registration/profile_results.html
{% extends "./base.html" %}
{% load static %}

{% block title %}Your Results{% endblock title %}

{% block inner_body %}

<section class="features bg-primary center-align">
    <div class="container">
        <div class="row">
            <div class="col s12 12 12 center-align">
                <div class="section-heading">
                    <h2>Your Results</h2>
                    <p class="text-muted">You can change them anytime in <a href="{% url 'user_registration:base_interests' %}">Interests</a></p>
                    <hr>
                </div>
            </div>
        </div>

        {% if results %}
        <table class="centered highlight">
          <thead>
            <tr>
              <th>Characteristic</th>
              <th>Average</th>
            </tr>
          </thead>

          <tbody>
            {% for key, value in results %}
              <tr>
                <td>{{ key }}</td>
                <td>{{ value }}</td>
              </tr>
              {% endfor %}
          </tbody>
        </table>
          {% else %}
                <h3>There are no results to Show. You need to complete the questionnaire in your profile.</h3>
          {% endif %}
    </div>
</section>

{% endblock inner_body %}

duyuo/user_registration/templates/user_registration/register.html
{% extends "./base.html" %}
{% load static %}

{% block title %}Duyo - Registration{% endblock title %}

{% block inner_body %}

<section id="register" class="download bg-primary center-align">
  <div class="section">
    <div class="row">
      <div class="col s12 m8 l8 offset-m2 offset-l2">
        <h4 >Okay, let's get started on Greatness!</h4>
        {% block register_login %}
          {% if not request.user.is_authenticated %}
            <form action="{% url 'user_registration:register_user' %}" method="POST" class="form-horizontal">
                            {% csrf_token %}
                            <div class="col s12 12 12">
                            {{ registration_form.as_p }}
                            </div>
                            <div class="form-group">
                                <div class="col-sm-offset-2 col-sm-8">
                                    <button type="submit" value="register_user" class="btn btn-large">Register</button>
                                </div>
                        </div>
                    </form>
                    {% else %}
                    <div class="card-panel teal">
              <span class="white-text">You are already registered! Awesome. Kinda weird that you are here though. You can go <a href="{% url 'user_registration:index' %}">home</a>.
              </span>
            </div>
                    {% endif %}
      {% endblock register_login %}
      </div>
    </div>
  </div>
</section>

{% endblock inner_body %}